In [6]:
from __future__ import print_function
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

In [7]:
# Get graph handle
sess = tf.Session()

### Introduce tensors in tf

In [8]:
my_tensor = tf.zeros([1,20])
print(my_tensor)

Tensor("zeros:0", shape=(1, 20), dtype=float32)


In [9]:
# Declare a variable
my_var = tf.Variable(tf.zeros([1,20]))
print(my_var)

<tf.Variable 'Variable:0' shape=(1, 20) dtype=float32_ref>


In [11]:
# Different kinds of variables
row_dim = 2
col_dim = 3 

In [12]:
# Zero initialized variable
zero_var = tf.Variable(tf.zeros([row_dim, col_dim]))
print(zero_var)

<tf.Variable 'Variable_1:0' shape=(2, 3) dtype=float32_ref>


In [13]:
# One initialized variable
ones_var = tf.Variable(tf.ones([row_dim, col_dim]))
print(ones_var)

<tf.Variable 'Variable_2:0' shape=(2, 3) dtype=float32_ref>


In [30]:
# shaped like other variable
sess.run(zero_var.initializer)
sess.run(ones_var.initializer)
zero_similar = tf.Variable(tf.zeros_like(zero_var))
ones_similar = tf.Variable(tf.ones_like(ones_var))

sess.run(ones_similar.initializer)
sess.run(zero_similar.initializer)

# print all variables
for var in [zero_var, ones_var, zero_similar, ones_similar]:
    print(sess.run(var))

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [31]:
# Fill shape with a constant
fill_var = tf.Variable(tf.fill([row_dim, col_dim], -1))

In [32]:
# Create a variable from a constant
const_var = tf.Variable(tf.constant([8, 6, 7, 5, 3, 0, 9]))

In [33]:
# This can also be used to fill an array:
const_fill_var = tf.Variable(tf.constant(-1, shape=[row_dim, col_dim]))

In [34]:
# Sequence generation
linear_var = tf.Variable(tf.linspace(start=0.0, stop=1.0, num=3)) # Generates [0.0, 0.5, 1.0] includes the end

sequence_var = tf.Variable(tf.range(start=6, limit=15, delta=3)) # Generates [6, 9, 12] doesn't include the end

### Random Numbers

In [37]:
# Random Normal
rnorm_var = tf.random_normal([row_dim, col_dim], mean=0.0, stddev=1.0)
print(sess.run(rnorm_var))

[[ 0.33355048 -0.08728082  0.70345742]
 [ 0.86420143  1.39855552  0.71620607]]


In [ ]:
# Initialize operation
initialize_op = tf.initialize_all_variables()

In [ ]:
# Add summaries to tensorboard
merged = tf.merge_all_summaries()

In [ ]:
# Initialize graph writer:
writer = tf.train.SummaryWriter("/tmp/tflog", sess.graph_def)

In [ ]:
# Run initialization of variable
sess.run(initialize_op)

Additional Features

In [ ]:
# 2-D tensor `a`
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3]) => [[1. 2. 3.]
                                                      [4. 5. 6.]]
# 2-D tensor `b`
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2]) => [[7. 8.]
                                                         [9. 10.]
                                                         [11. 12.]]
c = tf.matmul(a, b) => [[58 64]
                        [139 154]]

# 3-D tensor `a`
a = tf.constant(np.arange(1, 13, dtype=np.int32),
                shape=[2, 2, 3])                  => [[[ 1.  2.  3.]
                                                       [ 4.  5.  6.]],
                                                      [[ 7.  8.  9.]
                                                       [10. 11. 12.]]]

# 3-D tensor `b`
b = tf.constant(np.arange(13, 25, dtype=np.int32),
                shape=[2, 3, 2])                   => [[[13. 14.]
                                                        [15. 16.]
                                                        [17. 18.]],
                                                       [[19. 20.]
                                                        [21. 22.]
                                                        [23. 24.]]]
c = tf.matmul(a, b) => [[[ 94 100]
                         [229 244]],
                        [[508 532]
                         [697 730]]]

# Since python >= 3.5 the @ operator is supported (see PEP 465).
# In TensorFlow, it simply calls the `tf.matmul()` function, so the
# following lines are equivalent:
d = a @ b @ [[10.], [11.]]
d = tf.matmul(tf.matmul(a, b), [[10.], [11.]])

In [8]:
print(tf.constant([1, 2, 3, 4, 5, 6, 7]))

Tensor("Const_3:0", shape=(7,), dtype=int32)


In [11]:
print(tf.constant([1, 2, 3, 4, 5, 6], shape=(3, 2)))

Tensor("Const_5:0", shape=(3, 2), dtype=int32)


In [14]:
print(tf.zeros((3,2)))

Tensor("zeros_1:0", shape=(3, 2), dtype=float32)


In [17]:
y = tf.placeholder(tf.float32, shape=[None, 1024]) #all knonw

In [18]:
print(y)

Tensor("Placeholder_1:0", shape=(?, 1024), dtype=float32)


In [23]:
c = tf.constant([[1, 2], [3, 4], [5, 6]])
shuff = tf.random_shuffle(c)

In [25]:
sess = tf.Session()
print(sess.run(shuff))

[[3 4]
 [5 6]
 [1 2]]


In [35]:
mymat = tf.Variable([[7],[3]], tf.int16)

In [36]:
print(mymat)

<tf.Variable 'Variable_2:0' shape=(2, 1) dtype=int32_ref>
